services:
  api:
    build: .
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
      PORT: 3000
      DB_DIALECT: postgres
      DATABASE_URL: postgres://delivery:delivery@postgres:5432/delivery
      DB_SYNC: 'true'
      JWT_SECRET: local-dev-secret
      REDIS_URL: redis://redis:6379
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: delivery
      POSTGRES_PASSWORD: delivery
      POSTGRES_DB: delivery
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  pgadmin:
    image: dpage/pgadmin4:8
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  redis_data:
  pgadmin_data:
