services:
  - type: web
    name: delivery-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_DIALECT
        value: postgres
      - key: DB_SYNC
        value: 'true'
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: delivery-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: delivery-redis
          property: connectionString

  - type: keyvalue
    name: delivery-redis
    plan: free
    maxmemoryPolicy: noeviction
    ipAllowList: []

databases:
  - name: delivery-postgres
    plan: free
    databaseName: delivery
    user: delivery
